"""
PlatformIO extra_script that converts real web asset source files
(assets/src/*.html, *.css, *.js, *.svg, ...) into PROGMEM C++ headers
(assets/*.h) that get #included and compiled into the firmware.

This exists so asset authors can write real .html/.js/.css files - with
working editor syntax highlighting/linting - instead of hand-typing raw
string literals inside .h files. The generated headers are still committed
to git (same convention as version_autogen.h): anything consuming this
repo as a pinned lib_dep never runs this script itself, so the checked-in
headers must always be up to date. Run it (via `pio run`/`pio test`, which
invoke it automatically as an extra_script) after touching any file under
assets/src/ and commit the regenerated header alongside your source change.

Naming convention (no config needed for the common case): a source file
assets/src/<name>.<ext> generates assets/<name>_<ext>.h, with the PROGMEM
array named <NAME>_<EXT> and the include guard <NAME>_<EXT>_H. Add an
entry to assets/asset_manifest.json (relative source path -> partial
override dict) for the rare file that needs a different header filename,
variable name, or guard than the mechanical convention would produce -
see that file's comment for the exact schema.

Works standalone too: `python scripts/generate_web_assets.py [project_dir]`.
"""

import json
import os
import re
import sys

try:
    Import("env")  # noqa: F821 - injected by SCons when run as an extra_script
    PROJECT_DIR = env.subst("$PROJECT_DIR")
except NameError:
    PROJECT_DIR = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()

ASSETS_DIR = os.path.join(PROJECT_DIR, "assets")
SRC_DIR = os.path.join(ASSETS_DIR, "src")
MANIFEST_PATH = os.path.join(ASSETS_DIR, "asset_manifest.json")

# Extensions this script knows how to embed. All are treated as text; there
# are no binary assets anywhere in this ecosystem today (the one asset that
# looks binary, favicon.ico, is actually inline SVG - see asset_manifest.json).
TEXT_EXTENSIONS = {"html", "css", "js", "svg", "json", "txt"}

# Candidate raw-string delimiters, tried in order until one doesn't collide
# with `)<delim>"` appearing in the file's own content.
DELIMITER_CANDIDATES = ["", "rawliteral", "HTML", "CSS", "JS", "ASSET1", "ASSET2"]

AUTOGEN_BANNER = "// Auto-generated by scripts/generate_web_assets.py - DO NOT EDIT BY HAND"


def load_manifest():
    if not os.path.isfile(MANIFEST_PATH):
        return {}
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def default_names(relpath):
    # relpath is relative to assets/src, e.g. "web_platform_styles.css"
    stem, ext = os.path.splitext(relpath)
    ext = ext.lstrip(".")
    stem = re.sub(r"[^A-Za-z0-9]+", "_", stem).strip("_")
    slug = f"{stem}_{ext}"
    return {
        "header": f"{slug.lower()}.h",
        "var": slug.upper(),
        "guard": f"{slug.upper()}_H",
    }


def pick_delimiter(content):
    for delim in DELIMITER_CANDIDATES:
        if f'){delim}"' not in content:
            return delim
    raise ValueError(
        "Could not find a safe raw-string delimiter - content collides with "
        "every candidate in DELIMITER_CANDIDATES"
    )


def render_header(guard, var, content):
    delim = pick_delimiter(content)
    return (
        f"{AUTOGEN_BANNER}\n"
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        f"#include <Arduino.h>\n\n"
        f'const char {var}[] PROGMEM = R"{delim}(\n'
        f"{content}\n"
        f'){delim}";\n\n'
        f"#endif // {guard}\n"
    )


def generate():
    if not os.path.isdir(SRC_DIR):
        return  # nothing to do - this project has no assets/src yet

    manifest = load_manifest()
    generated_headers = set()

    for entry in sorted(os.listdir(SRC_DIR)):
        src_path = os.path.join(SRC_DIR, entry)
        if not os.path.isfile(src_path):
            continue
        ext = entry.rsplit(".", 1)[-1].lower() if "." in entry else ""
        if ext not in TEXT_EXTENSIONS:
            print(f"[generate_web_assets] Skipping {entry}: unrecognized extension")
            continue

        names = default_names(entry)
        names.update(manifest.get(entry, {}))
        generated_headers.add(names["header"])

        with open(src_path, "r", encoding="utf-8") as f:
            content = f.read().rstrip("\n")

        header_content = render_header(names["guard"], names["var"], content)
        header_path = os.path.join(ASSETS_DIR, names["header"])

        existing = None
        if os.path.isfile(header_path):
            with open(header_path, "r", encoding="utf-8") as f:
                existing = f.read()

        if existing != header_content:
            with open(header_path, "w", encoding="utf-8", newline="\n") as f:
                f.write(header_content)
            print(f"[generate_web_assets] Wrote {names['header']} (from {entry})")

    # Flag generated .h files under assets/ that no longer have a matching
    # source/manifest entry - likely a rename that needs cleanup, but we
    # never delete automatically.
    if os.path.isdir(ASSETS_DIR):
        for entry in os.listdir(ASSETS_DIR):
            full = os.path.join(ASSETS_DIR, entry)
            if (
                os.path.isfile(full)
                and entry.endswith(".h")
                and entry not in generated_headers
            ):
                with open(full, "r", encoding="utf-8") as f:
                    first_line = f.readline()
                if AUTOGEN_BANNER in first_line:
                    print(
                        f"[generate_web_assets] WARNING: {entry} looks generated "
                        "but has no matching assets/src/ file or manifest entry "
                        "anymore - stale? (not deleting automatically)"
                    )


generate()
